### ISSUE TITLE
フロントエンド環境整備

### ISSUE THREAD

**Issue by ghost** [tentotech/spajam#10]

**Comment by sosukesuzuki** [comment]
死日亜

**Comment by ghost** [comment]
https://github.com/wh11e/frontend.g8
TypeScriptであることとかRedux-Observableを使っているところとかを無視すればコピペできると思う

**Comment by ghost** [comment]
コピペコードはいいぞ

2017/05/27 午後1:58 "Tomoki Ohno" <notifications@github.com>:

**Comment by ghost** [comment]
澤村
