### ISSUE TITLE
おしっこ

### ISSUE THREAD

**Issue by ghostrick** [tentotech/spajam#70]

**Comment by sosukesuzuki** [comment]
# 汚いのでやめて

**Comment by ghost** [comment]
![](https://img.gifmagazine.net/gifmagazine/images/3503/original.gif?1402160273)

**Comment by ghostrick** [comment]
![c5u626qvmaeqlf3 1](https://cloud.githubusercontent.com/assets/11712555/26526220/fb8fcc50-43ad-11e7-8777-116431c32d77.jpg)
